# Generated by Django 5.0 on 2024-01-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_regmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('job_title', models.CharField(max_length=20)),
                ('work', models.CharField(max_length=20)),
                ('exp', models.IntegerField()),
                ('job_type', models.CharField(max_length=20)),
            ],
        ),
    ]
