# Generated by Django 5.0 on 2024-01-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_jobsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsmodel',
            old_name='job_title',
            new_name='jt',
        ),
        migrations.RenameField(
            model_name='jobsmodel',
            old_name='job_type',
            new_name='jtyp',
        ),
        migrations.RenameField(
            model_name='jobsmodel',
            old_name='work',
            new_name='wt',
        ),
    ]
