# Generated by Django 5.0 on 2024-01-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_rename_job_title_jobsmodel_jt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=255)),
                ('work_type', models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('experience', models.CharField(choices=[('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('4-5', '4-5'), ('5-6', '5-6')], max_length=20)),
                ('job_type', models.CharField(choices=[('Part time', 'Part time'), ('Full time', 'Full time')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='jobsmodel',
        ),
    ]
