# Generated by Django 5.0 on 2024-01-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_job_delete_jobsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg2model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=20)),
                ('work_type', models.CharField(max_length=20)),
                ('exp', models.CharField(max_length=20)),
                ('job_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
