# Generated by Django 5.0 on 2024-01-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_reg2model_delete_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobapplymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=12)),
                ('experience', models.CharField(max_length=30)),
                ('resume', models.FileField(upload_to='jobapp/static')),
            ],
        ),
    ]
